// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZ0HtLqtWgGYndYJxRwQCpWQlWcLgSiA',
    appId: '1:178969593991:web:fbd46628d81e9d7ec81022',
    messagingSenderId: '178969593991',
    projectId: 'parasdigital-fd052',
    authDomain: 'parasdigital-fd052.firebaseapp.com',
    storageBucket: 'parasdigital-fd052.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWV6FMk6Nf3UfNKaHrIn1aPrFJzSsRxxw',
    appId: '1:178969593991:android:91f51b9d38eee9f8c81022',
    messagingSenderId: '178969593991',
    projectId: 'parasdigital-fd052',
    storageBucket: 'parasdigital-fd052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMccZjcBARiGjUeOlHD6BtNvmxspFRCII',
    appId: '1:178969593991:ios:4c82463571628633c81022',
    messagingSenderId: '178969593991',
    projectId: 'parasdigital-fd052',
    storageBucket: 'parasdigital-fd052.appspot.com',
    iosClientId: '178969593991-h4vesf7srd1ogqnshoafd8glo21cu7mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.parasDigitalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMccZjcBARiGjUeOlHD6BtNvmxspFRCII',
    appId: '1:178969593991:ios:4c82463571628633c81022',
    messagingSenderId: '178969593991',
    projectId: 'parasdigital-fd052',
    storageBucket: 'parasdigital-fd052.appspot.com',
    iosClientId: '178969593991-h4vesf7srd1ogqnshoafd8glo21cu7mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.parasDigitalTest',
  );
}
